%%% Copyright (c) Meta Platforms, Inc. and affiliates. All rights reserved.
%%%
%%% This source code is licensed under the Apache 2.0 license found in
%%% the LICENSE file in the root directory of this source tree.

-module(skip_me_pb).
% Generated by gpb_compile
% Previous comment is a lie for testing

-export([skipped/0]).

-spec skipped() -> skipped.
skipped() ->
  200.
