jobs:
  linux-release-otp-25:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Set up GraalVM
        uses: "DeLaGuardo/setup-graalvm@5.0"
        with:
          graalvm: '22.1.0'
          java: 'java11'
      - name: Install Native Image Plugin
        run: gu install native-image
      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.2'
          rebar3-version: '3.20.0'
      - name: Assemble eqwalizer.jar
        run: "cd eqwalizer; sbt assembly"
      - name: Assemble eqwalizer binary
        run: "cd eqwalizer && native-image -H:IncludeResources=application.conf --no-server --no-fallback -jar target/scala-2.13/eqwalizer.jar eqwalizer"
      - name: Test elp
        run: "cd mini-elp && cargo test --workspace"
      - name: Assemble elp
        run: "export ELP_EQWALIZER_PATH=$GITHUB_WORKSPACE/eqwalizer/eqwalizer && cd mini-elp && cargo build --release"
      - name: Add elp to path
        run: 'echo "$GITHUB_WORKSPACE/mini-elp/target/release" >> $GITHUB_PATH'
      - name: Test eqwalizer
        run: 'cd eqwalizer && sbt test'
      - name: Upload eqwalizer.jar
        uses: "actions/upload-artifact@v2"
        with:
          name: eqwalizer.jar
          path: eqwalizer/target/scala-2.13/eqwalizer.jar
      - name: Upload eqwalizer native binary
        uses: "actions/upload-artifact@v2"
        with:
          name: eqwalizer
          path: eqwalizer/eqwalizer
      - name: Make elp-linux.tar.gz
        run: 'tar -zcvf elp-linux.tar.gz -C mini-elp/target/release/ elp'
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: get_release_url
        name: Get release url
        uses: "bruceadams/get-release@v1.3.2"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: Upload release elp-linux.tar.gz
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          asset_content_type: application/octet-stream
          asset_name: elp-linux.tar.gz
          asset_path: elp-linux.tar.gz
          upload_url: "${{ steps.get_release_url.outputs.upload_url }}"
  linux-release-otp-23:
    needs:
      - linux-release-otp-25
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Set up GraalVM
        uses: "DeLaGuardo/setup-graalvm@5.0"
        with:
          graalvm: '22.1.0'
          java: 'java11'
      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23.3'
          rebar3-version: '3.20.0'
      - name: Download eqwalizer.jar
        uses: "actions/download-artifact@v2"
        with:
          name: eqwalizer.jar
          path: eqwalizer/target/scala-2.13
      - name: Download eqwalizer binary
        uses: "actions/download-artifact@v2"
        with:
          name: eqwalizer
          path: eqwalizer
      - name: Test elp
        run: "cd mini-elp && cargo test --workspace"
      - name: Assemble elp
        run: "export ELP_EQWALIZER_PATH=$GITHUB_WORKSPACE/eqwalizer/eqwalizer && cd mini-elp && cargo build --release"
      - name: Make elp-linux-otp-23.tar.gz
        run: 'tar -zcvf elp-linux-otp-23.tar.gz -C mini-elp/target/release/ elp'
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: get_release_url
        name: Get release url
        uses: "bruceadams/get-release@v1.3.2"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: Upload release elp-linux-otp-23.tar.gz
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          asset_content_type: application/octet-stream
          asset_name: elp-linux-otp-23.tar.gz
          asset_path: elp-linux-otp-23.tar.gz
          upload_url: "${{ steps.get_release_url.outputs.upload_url }}"
  macos-release:
    needs:
      - linux-release-otp-25
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Set up GraalVM
        uses: "DeLaGuardo/setup-graalvm@5.0"
        with:
          graalvm: '22.1.0'
          java: 'java11'
      - name: Install Native Image Plugin
        run: gu install native-image
      - name: Install erlang + rebar3
        run: brew install erlang rebar3
      - name: Set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download eqwalizer.jar
        uses: "actions/download-artifact@v2"
        with:
          name: eqwalizer.jar
          path: eqwalizer/target/scala-2.13
      - name: Assemble eqwalizer binary
        run: "cd eqwalizer && native-image -H:IncludeResources=application.conf --no-server --no-fallback -jar target/scala-2.13/eqwalizer.jar eqwalizer"
      - name: Test elp
        run: "export ELP_EQWALIZER_PATH=$GITHUB_WORKSPACE/eqwalizer/eqwalizer && cd mini-elp && cargo test --workspace"
      - name: Assemble elp
        run: "export ELP_EQWALIZER_PATH=$GITHUB_WORKSPACE/eqwalizer/eqwalizer && cd mini-elp && cargo build --release"
      - name: Make elp-macos.tar.gz
        run: 'tar -zcvf elp-macos.tar.gz -C mini-elp/target/release/ elp'
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: get_release_url
        name: Get release url
        uses: "bruceadams/get-release@v1.3.2"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: Upload release elp-macos.tar.gz
        uses: "actions/upload-release-asset@v1.0.2"
        with:
          asset_content_type: application/octet-stream
          asset_name: elp-macos.tar.gz
          asset_path: elp-macos.tar.gz
          upload_url: "${{ steps.get_release_url.outputs.upload_url }}"
name: eqWAlizer release
on:
  release:
    types:
      - created
